### ISSUE TITLE
Setup Express server

### ISSUE THREAD

**Issue by guylepage3** [papriika/papriika.com#14]
**Description**
Refactor app to include express server in preparation for adding a newsletter form. See #16

**Comment by guylepage3** [comment]
https://medium.freecodecamp.org/how-to-deploy-a-react-app-with-an-express-server-on-heroku-32244fe5a250

**Comment by guylepage3** [comment]
By running the 2 steps above I was able to test and see that the paths were off.

I had set the `homepage` paths in both server and client's `package.json` file to something other than `"."`.

NOTE: Always ensure `homepage` paths are set to `"."`.

**Comment by guylepage3** [comment]
Done

**Comment by faddat** [comment]
In the end, this was deployed on haroku correct?

**Comment by guylepage3** [comment]
Yes but to run the app locally I used this process.. https://github.com/papriika/papriika.com/issues/14#issuecomment-462288386
